### ISSUE TITLE
Article to add

### ISSUE THREAD

**Issue by SylvatiCodes** [karpathy/covid-sanity#1]
https://www.frontiersin.org/articles/10.3389/fvets.2018.00084/full

Article title "Geographical and Historical Patterns in the Emergences of Novel Highly Pathogenic Avian Influenza (HPAI) H5 and H7 Viruses in Poultry"

Haven't got the time to fork, look through how to add manually, and PR. Sorry.

**Comment by karpathy** [comment]
Thank you for the pointer, but there is no mechanism right now to manually add articles to the page.
