### ISSUE TITLE
Error on running flask run

### ISSUE THREAD

**Issue by ankitsharma1999** [karpathy/covid-sanity#3]
The following error message is displayed on running `flask run` after `python3 run.py`
`Error: Could not locate a Flask application. You did not provide the "FLASK_APP" environment variable, and a "wsgi.py" or "app.py" module was not found in the current directory`

**Comment by karpathy** [comment]
Oh yeah you have to export `FLASK_APP`, I missed that. Modifying the README to reflect, thank you!

**Comment by ankitsharma1999** [comment]
My pleasure
