### ISSUE TITLE
Search Terms Examples

### ISSUE THREAD

**Issue by starkfree** [karpathy/covid-sanity#5]
I might have just overlooked it, but do you provide an example anywhere of how a person might customize the search terms being used? On quick glance, it seems like these would go in a search.json file, but there is currently none provided in the repo, and I didn't see a sample of how the file would be formatted. 

Could you perhaps provide the search.json file being used currently to filter for COVID-19 related terms as a starting point for customization?

Thanks!

**Comment by karpathy** [comment]
`search.json` is computed automatically in `run.py` as a result of the scikit-learn tokenizer. There is no way to manually add search terms right now. In principle there could be a manual list. What is an example of what you'd like to add?

**Comment by starkfree** [comment]
Apologies, I just now realized the papers are being compiled by biorxiv at this URL
https://connect.biorxiv.org/relate/collection_json.php?grp=181

I assumed you were filtering them after the fact. Sorry for the confusion.
